### ISSUE TITLE
CRUD operations not working with schema provided

### ISSUE THREAD

**Issue by bingyu11** [pip-services3-python/pip-services3-postgres-python#3]
I initialized the postgres persistence with a schema (e.g. schema), and created a table (e.g. table) under that schema (done by `_ensure_schema` frunction). Then all the CRUD operations don't work anymore with the error `relation "table"schema.table" does not exist`.

Should the variable `builder` be overwritten instead of being concatenated with itself in the function `PostgresPersistence::_quoted_table_name()`?

https://github.com/pip-services3-python/pip-services3-postgres-python/blob/adfccb9fcb36dd7d892c93b537ebe2fe850eb67e/pip_services3_postgres/persistence/PostgresPersistence.py#L301

**Comment by banalna** [comment]
Fixed since version 3.2.7. Thank you!
